# Generated by Django 4.2.7 on 2026-05-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tender_management_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='company',
            new_name='tenders_com_company_d7cad3_idx',
            old_name='tenders_com_company_8f0b8d_idx',
        ),
        migrations.AlterField(
            model_name='offeritem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, help_text='Quoted quantity (may match or partially cover tender item quantity).', max_digits=14),
        ),
    ]
