# Generated by Django 4.2.7 on 2026-05-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_rename_tenders_com_company_8f0b8d_idx_tenders_com_company_d7cad3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
