# Generated by Django 4.2.7 on 2026-05-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_tender_input_sources'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
