# Generated by Django 4.2.7 on 2026-05-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_tender_analysis_workpackage_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='tender_type',
            field=models.CharField(blank=True, help_text='Legacy/free-form type label; prefer visibility for public vs private.', max_length=50),
        ),
    ]
