# Generated by Django 4.2.7 on 2026-06-27 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0012_procurement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='procurement',
            new_name='tenders_pro_status_5515fe_idx',
            old_name='tenders_pro_status_8a1f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='procurement',
            new_name='tenders_pro_categor_643fcb_idx',
            old_name='tenders_pro_categor_4b9e1a_idx',
        ),
    ]
