# Generated by Django 4.2.7 on 2026-07-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0015_tender_definition_demo_workflow'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenderimportrecord',
            new_name='tenders_ten_tender__77125c_idx',
            old_name='tenders_ti_def_ext_idx',
        ),
        migrations.RenameIndex(
            model_name='tenderimportrecord',
            new_name='tenders_ten_tender__28bf86_idx',
            old_name='tenders_ti_def_ref_idx',
        ),
    ]
