# Generated by Django 4.2.7 on 2026-02-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('floorplan_file', models.FileField(upload_to='floorplans/')),
                ('style_preference', models.JSONField(default=dict)),
                ('ai_generated_images', models.JSONField(default=list)),
            ],
        ),
    ]
