# Generated by Django 4.2.7 on 2026-04-17 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cvs/')),
                ('aplicant_name', models.CharField(max_length=255)),
                ('score', models.FloatField(null=True)),
                ('processed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('duration_seconds', models.IntegerField(default=120)),
                ('score', models.FloatField(blank=True, help_text='Final interview test score (0-100). Calculated once on answer submission.', null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='hr.cv')),
                ('interviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='interview_videos/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interview_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_submissions', to='hr.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('option_1', models.CharField(max_length=255)),
                ('option_2', models.CharField(max_length=255)),
                ('option_3', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3')], max_length=10)),
                ('interview_session', models.ForeignKey(blank=True, help_text='When set, this question is part of that interview room (not shown globally).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_questions', to='hr.interviewsession')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_company', models.CharField(max_length=255)),
                ('job_location', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_responsibilities', models.TextField()),
                ('job_requirements', models.TextField()),
                ('job_benefits', models.TextField()),
                ('job_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_type', models.CharField(max_length=255)),
                ('job_category', models.CharField(max_length=255)),
                ('job_subcategory', models.CharField(max_length=255)),
                ('job_subsubcategory', models.CharField(max_length=255)),
                ('job_published', models.BooleanField(default=False)),
                ('job_published_at', models.DateTimeField(blank=True, null=True)),
                ('job_created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost'),
        ),
        migrations.AddField(
            model_name='cv',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who submitted this CV (for candidate-scoped APIs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cvs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.CharField(choices=[('option_1', 'Option 1'), ('option_2', 'Option 2'), ('option_3', 'Option 3')], max_length=10)),
                ('interview_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hr.interviewsession')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='hr.question')),
            ],
        ),
    ]
