# Generated by Django 4.2.7 on 2026-04-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_salary',
        ),
    ]
