# Generated by Django 4.2.7 on 2026-04-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_remove_jobpost_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_salary_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_salary_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
