# Generated by Django 4.2.7 on 2026-04-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_jobpost_job_salary_max_jobpost_job_salary_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='job_subsubcategory',
        ),
    ]
