# Generated by Django 4.2.7 on 2026-05-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_candidate_jobposting_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hr.jobpost'),
        ),
    ]
